const NATURAL_NUMBER = "natural";
const WHOLE_NUMBER = "whole";
const INTEGER_NUMBER = "integer";
const RATIONAL_NUMBER = "rational";
const IRRATIONAL_NUMBER = "irrational";
const COMPLEX_NUMBER = "complex";
const POSSIBLE_NUMBER_TYPES = [NATURAL_NUMBER, WHOLE_NUMBER, INTEGER_NUMBER, RATIONAL_NUMBER, IRRATIONAL_NUMBER, COMPLEX_NUMBER];

module.exports = {
    NATURAL_NUMBER,
    WHOLE_NUMBER,
    INTEGER_NUMBER,
    RATIONAL_NUMBER,
    IRRATIONAL_NUMBER,
    COMPLEX_NUMBER,
    POSSIBLE_NUMBER_TYPES
};