const ADDITION = "addition"
const ADDITION_SYMBOL = "+"
const ADDITION_LATEX_SYMBOL = "+"
const SUBTRACTION = "subtraction"
const SUBTRACTION_SYMBOL = "-"
const SUBTRACTION_LATEX_SYMBOL = "-"
const MULTIPLICATION = "multiplication"
const MULTIPLICATION_SYMBOL = "*"
const MULTIPLICATION_LATEX_SYMBOL = "\times"
const DIVISION = "division"
const DIVISION_SYMBOL = "÷"
const DIVISION_LATEX_SYMBOL = "/"
const ARRAY_OF_SIMPLE_OPERATIONS = [ADDITION, SUBTRACTION, MULTIPLICATION, DIVISION];

module.exports = {
    ADDITION,
    ADDITION_SYMBOL,
    ADDITION_LATEX_SYMBOL,
    SUBTRACTION,
    SUBTRACTION_SYMBOL,
    SUBTRACTION_LATEX_SYMBOL,
    MULTIPLICATION,
    MULTIPLICATION_SYMBOL,
    MULTIPLICATION_LATEX_SYMBOL,
    DIVISION,
    DIVISION_SYMBOL,
    DIVISION_LATEX_SYMBOL,
    ARRAY_OF_SIMPLE_OPERATIONS
  };
  